### ISSUE TITLE
Won't load on *nix due to pathing issue

### ISSUE THREAD

**Issue by WizardCM** [tielqt/sparrow-for-mixer#1]
https://github.com/tielqt/sparrow-for-mixer/blob/e84ba3773cf01fb3b2bea59ecad6b67c41cf6fb9/index.js#L40

Changing this line to `/views` fixes this particular issue. It *should* still work on Windows.

**Comment by evieveevee** [comment]
I've confirmed this fix works, and it's available in Release 0.0.2.
