### ISSUE TITLE
Ports are hard coded but should be moved to config

### ISSUE THREAD

**Issue by WizardCM** [tielqt/sparrow-for-mixer#3]
https://github.com/tielqt/sparrow-for-mixer/blob/9e2ce0487ac9063adf575078e2984d908c90ccc7/index.js#L117

https://github.com/tielqt/sparrow-for-mixer/blob/9e2ce0487ac9063adf575078e2984d908c90ccc7/index.js#L118

https://github.com/tielqt/sparrow-for-mixer/blob/9e2ce0487ac9063adf575078e2984d908c90ccc7/index.js#L124

**Comment by evieveevee** [comment]
Added this feature for 0.0.3. Commit 85f389b.
